name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pylint
          pip install --upgrade PyQt5
          pip install --upgrade -r requirements.txt
          pip show PyQt5
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
